name: Run Python Tests

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - main  # Run tests on pushes to the "main" branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the "main" branch

# Define the jobs
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Step 4: Run the tests
      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"